name: Commitlint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - uses: actions/checkout@v4

      - name: Run commitlint
        id: commitlintrun
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: opensource-nepal/commitlint@v0.2.1
        with:
          fail_on_error: false

      - name: Check Output
        run: |
          echo 'Status - ${{ steps.commitlintrun.outputs.status }}'
          echo 'Exit Code - ${{ steps.commitlintrun.outputs.exit_code }}'

          # Check commitlintrun status
          if [ "${{ steps.commitlintrun.outputs.status }}" = "failure" ]; then
            echo "Failing the job manually because Commitlint status is failure."
            exit 1
          fi
